version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile.api
    container_name: shopassist_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      # Mount the lib directory into the API container
      - ./src/lib:/app/lib
  ui:
    build:
      context: .
      dockerfile: src/Dockerfile.gui
    container_name: shopassist_ui
    env_file:
      - .env
    ports:
      - "7860:7860"
    networks:
      - app-network
    volumes:
      # Mount the lib directory into the API container
      - ./src/lib:/app/lib
    restart: unless-stopped
  redis:
    image: redis:6.2-alpine
    container_name: shopassist_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:1.21
    container_name: shopassist_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - api
      - ui
    networks:
      - app-network

networks:
  app-network:
    driver: bridge